Update atom. Use atom-native + remove Java (#1789)
* Remove Java and atom from a number of images

Signed-off-by: Prabhu Subramanian <prabhu@appthreat.com>

* Use atom native binary for node 20, Java 11 and 17

Signed-off-by: Prabhu Subramanian <prabhu@appthreat.com>

* Use atom native binary for node 20, Java 11 and 17

Signed-off-by: Prabhu Subramanian <prabhu@appthreat.com>

* Include atom-tools for java 17

Signed-off-by: Prabhu Subramanian <prabhu@appthreat.com>

* Bug fix

Signed-off-by: Prabhu Subramanian <prabhu@appthreat.com>

---------

Signed-off-by: Prabhu Subramanian <prabhu@appthreat.com>

diff --git a/ci/base-images/cdxgen/Dockerfile.node20 b/ci/base-images/cdxgen/Dockerfile.node20
--- a/ci/base-images/cdxgen/Dockerfile.node20
+++ b/ci/base-images/cdxgen/Dockerfile.node20
@@ -13,12 +13,31 @@ LABEL maintainer="CycloneDX" \
 
 ENV CDXGEN_IN_CONTAINER=true \
     NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
+    ATOM_CMD=/usr/local/bin/atom \
     PYTHONPATH=/opt/pypi:${PYTHONPATH}
 ENV PATH=${PATH}:/usr/local/bin:/opt/pypi/bin:/opt/cdxgen/node_modules/.bin:
 
 COPY . /opt/cdxgen
 
-RUN cd /opt/cdxgen && corepack enable && corepack pnpm install --config.strict-dep-builds=true --prod --package-import-method copy --frozen-lockfile && corepack pnpm cache delete \
+RUN set -e; \
+    ARCH_NAME="$(rpm --eval '%{_arch}')"; \
+    case "${ARCH_NAME##*-}" in \
+        'x86_64') \
+            ATOM_ARCH_SUFFIX='amd64'; \
+            ;; \
+        'arm64') \
+            ATOM_ARCH_SUFFIX='arm64'; \
+            ;; \
+        'aarch64') \
+            ATOM_ARCH_SUFFIX='arm64'; \
+            ;; \
+        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+    esac \
+    && cd /opt/cdxgen && corepack enable && corepack pnpm install --config.strict-dep-builds=true --prod --package-import-method copy --no-optional --frozen-lockfile && corepack pnpm cache delete \
+    && curl -L https://github.com/AppThreat/atom/releases/latest/download/atom-${ATOM_ARCH_SUFFIX} -o /usr/local/bin/atom \
+    && chmod +x /usr/local/bin/atom \
+    && /usr/local/bin/atom --help \
+    && npm install -g @appthreat/atom-parsetools \
     && mkdir -p /opt/cdxgen-node-cache \
     && node /opt/cdxgen/bin/cdxgen.js --help \
     && pip install --upgrade --no-cache-dir atom-tools --target /opt/pypi \
