Changed image builds to make use of Nexus on self-hosted runs. Also refactored & reordered Dockerfiles.
Signed-off-by: Roland Asmann <roland.asmann@gmail.com>

diff --git a/ci/images/Dockerfile.dotnet7 b/ci/images/Dockerfile.dotnet7
--- a/ci/images/Dockerfile.dotnet7
+++ b/ci/images/Dockerfile.dotnet7
@@ -1,18 +1,46 @@
 # Base-image
 FROM registry.suse.com/bci/dotnet-sdk:7.0 AS base
 
-ENV DOTNET_GENERATE_ASPNET_CERTIFICATE=false \
+ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
+    DOTNET_GENERATE_ASPNET_CERTIFICATE=false \
     DOTNET_NOLOGO=true \
+    DOTNET_RUNNING_IN_CONTAINER=true \
     DOTNET_USE_POLLING_FILE_WATCHER=false \
     NUGET_XMLDOC_MODE=skip \
-    DOTNET_RUNNING_IN_CONTAINER=true \
-    DOTNET_CLI_TELEMETRY_OPTOUT=1 \
+    PATH=${PATH}:/usr/local/bin \
+    PYTHONPATH=/opt/pypi \
     npm_config_python=/usr/bin/python3.11
-ENV PATH=${PATH}:/usr/local/bin
 
-RUN zypper refresh && zypper --non-interactive update && zypper --non-interactive install -l --no-recommends git-core nodejs20 npm20 python311 python311-pip wget zip unzip make gawk curl \
-    && npm install -g corepack \
-    && zypper clean -a
+RUN set -e; \
+    zypper refresh \
+ && zypper \
+      --non-interactive \
+        update \
+ && zypper \
+      --non-interactive \
+        install \
+        -l \
+        --no-recommends \
+          curl \
+          gawk \
+          git-core \
+          make \
+          nodejs20 \
+          npm20 \
+          python311 \
+          python311-pip \
+          unzip \
+          wget \
+          zip \
+ && pip install \
+      --no-cache-dir \
+      --target ${PYTHONPATH} \
+      --upgrade \
+        atom-tools \
+        blint \
+ && npm install -g \
+      corepack \
+ && zypper clean -a
 
 CMD ["/bin/bash"]
 
@@ -21,48 +49,57 @@ CMD ["/bin/bash"]
 # cdxgen-image
 FROM base AS cdxgen
 
+ARG VERSION=master
+
 LABEL maintainer="CycloneDX" \
+      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t $TAG -r /app --server" \
       org.opencontainers.image.authors="Team AppThreat <cloud@appthreat.com>" \
-      org.opencontainers.image.source="https://github.com/CycloneDX/cdxgen" \
-      org.opencontainers.image.url="https://github.com/CycloneDX/cdxgen" \
-      org.opencontainers.image.version="rolling" \
-      org.opencontainers.image.vendor="CycloneDX" \
+      org.opencontainers.image.description="Image with cdxgen SBOM generator for $LANGUAGE apps" \
       org.opencontainers.image.licenses="Apache-2.0" \
+      org.opencontainers.image.source="https://github.com/CycloneDX/cdxgen" \
       org.opencontainers.image.title="cdxgen" \
-      org.opencontainers.image.description="Rolling image with cdxgen SBOM generator for dotnet 7 apps" \
-      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t ghcr.io/cyclonedx/cdxgen-dotnet7:v11 -r /app --server"
+      org.opencontainers.image.url="https://github.com/CycloneDX/cdxgen" \
+      org.opencontainers.image.vendor="CycloneDX" \
+      org.opencontainers.image.version="$VERSION"
 
 ENV CDXGEN_IN_CONTAINER=true \
+    DOSAI_CMD=/usr/local/bin/dosai \
     NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
-    PYTHONPATH=/opt/pypi \
-    DOSAI_CMD=/usr/local/bin/dosai
-ENV PATH=${PATH}:/usr/local/bin:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin
+    PATH=${PATH}:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin
 
 COPY . /opt/cdxgen
 
 RUN set -e; \
     ARCH_NAME="$(rpm --eval '%{_arch}')"; \
-    url=; \
     case "${ARCH_NAME##*-}" in \
-        'x86_64') \
-            DOSAI_ARCH_SUFFIX='-full'; \
-            ;; \
-        'arm64') \
-            DOSAI_ARCH_SUFFIX='-linux-arm64-full'; \
-            ;; \
-        'aarch64') \
-            DOSAI_ARCH_SUFFIX='-linux-arm64-full'; \
-            ;; \
-        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+      'amd64' | 'x86_64') \
+        DOSAI_ARCH_SUFFIX='-full'; \
+        ;; \
+      'aarch64' | 'arm64') \
+        DOSAI_ARCH_SUFFIX='-linux-arm64-full'; \
+        ;; \
+      *) \
+        echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; \
+        exit 1 \
+        ;; \
     esac \
-    && cd /opt/cdxgen && corepack enable && corepack pnpm install --config.strict-dep-builds=true --prod --package-import-method copy --frozen-lockfile && corepack pnpm cache delete \
-    && curl -L https://github.com/owasp-dep-scan/dosai/releases/latest/download/Dosai${DOSAI_ARCH_SUFFIX} -o /usr/local/bin/dosai \
-    && chmod +x /usr/local/bin/dosai \
-    && dosai --help \
-    && mkdir -p ${NODE_COMPILE_CACHE} \
-    && node /opt/cdxgen/bin/cdxgen.js --help \
-    && pip install --upgrade --no-cache-dir blint atom-tools --target /opt/pypi \
-    && rm -rf /root/.cache/node \
-    && chmod a-w -R /opt
+ && cd /opt/cdxgen \
+ && corepack enable \
+ && corepack pnpm install \
+      --config.strict-dep-builds=true \
+      --frozen-lockfile \
+      --package-import-method copy \
+      --prod \
+ && corepack pnpm cache delete \
+ && curl -L https://github.com/owasp-dep-scan/dosai/releases/latest/download/Dosai${DOSAI_ARCH_SUFFIX} \
+      -o /usr/local/bin/dosai \
+ && chmod +x /usr/local/bin/dosai \
+ && dosai --help \
+ && mkdir -p ${NODE_COMPILE_CACHE} \
+ && node /opt/cdxgen/bin/cdxgen.js --help \
+ && rm -rf .npmrc /root/.cache/node \
+ && chmod a-w -R /opt
+
 WORKDIR /app
+
 ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
diff --git a/ci/images/debian/Dockerfile.swift6 b/ci/images/debian/Dockerfile.swift6
--- a/ci/images/debian/Dockerfile.swift6
+++ b/ci/images/debian/Dockerfile.swift6
@@ -1,73 +1,97 @@
 # Base-image
 FROM debian:12 AS base
 
-ARG SWIFT_SIGNING_KEY=52BB7E3DE28A71BE22EC05FFEF80A866B47A981F
-ARG SWIFT_PLATFORM=debian12
-ARG SWIFT_BRANCH=swift-6.1.2-release
-ARG SWIFT_VERSION=swift-6.1.2-RELEASE
-ARG SWIFT_WEBROOT=https://download.swift.org
 # renovate: datasource=docker depName=node
 ARG NODE_VERSION=22.17.0
+ARG SWIFT_BRANCH=swift-6.1.2-release
+ARG SWIFT_PLATFORM=debian12
+ARG SWIFT_SIGNING_KEY=52BB7E3DE28A71BE22EC05FFEF80A866B47A981F
+ARG SWIFT_VERSION=swift-6.1.2-RELEASE
+ARG SWIFT_WEBROOT=https://download.swift.org
 
-ENV SWIFT_SIGNING_KEY=$SWIFT_SIGNING_KEY \
-    SWIFT_PLATFORM=$SWIFT_PLATFORM \
+ENV NVM_DIR="/root/.nvm" \
+    PYTHONPATH=/opt/pypi \
     SWIFT_BRANCH=$SWIFT_BRANCH \
+    SWIFT_PLATFORM=$SWIFT_PLATFORM \
+    SWIFT_SIGNING_KEY=$SWIFT_SIGNING_KEY \
     SWIFT_VERSION=$SWIFT_VERSION \
-    SWIFT_WEBROOT=$SWIFT_WEBROOT \
-    NVM_DIR="/root/.nvm"
-
-ENV PATH=${PATH}:${NVM_DIR}/versions/node/v${NODE_VERSION}/bin:/usr/local/bin:/root/.local/bin
+    SWIFT_WEBROOT=$SWIFT_WEBROOT
+ENV PATH=${PATH}:/usr/local/bin:/root/.local/bin:${NVM_DIR}/versions/node/v${NODE_VERSION}/bin
 
 COPY ci/images/debian/install.sh /tmp/
 
 RUN set -e; \
     ARCH_NAME="$(dpkg --print-architecture)"; \
-    url=; \
     case "${ARCH_NAME##*-}" in \
-        'amd64') \
-            OS_ARCH_SUFFIX=''; \
-            ;; \
-        'arm64') \
-            OS_ARCH_SUFFIX='-aarch64'; \
-            ;; \
-        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+      'amd64' | 'x86_64') \
+        OS_ARCH_SUFFIX=''; \
+        ;; \
+      'aarch64' | 'arm64') \
+        OS_ARCH_SUFFIX='-aarch64'; \
+        ;; \
+      *) \
+        echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; \
+        exit 1 \
+        ;; \
     esac; \
-    export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && apt-get -q update && \
-    apt-get -q install -y \
-        build-essential python3 python3-pip python3-dev locales bash bzip2 git-core zip unzip make gawk \
-        curl gpg \
+    export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
+ && apt-get -q update \
+ && apt-get -q install -y \
+        bash \
         binutils-gold \
-        libicu-dev \
+        build-essential \
+        bzip2 \
+        curl \
+        gawk \
+        gcc \
+        git \
+        git-core \
+        gpg \
         libcurl4-openssl-dev \
         libedit-dev \
-        libsqlite3-dev \
+        libicu-dev \
         libncurses-dev \
         libpython3-dev \
+        libsqlite3-dev \
         libxml2-dev \
+        locales \
+        make \
         pkg-config \
-        uuid-dev \
+        python3 \
+        python3-dev \
+        python3-pip \
         tzdata \
-        git \
-        gcc \
-    && SWIFT_WEBDIR="$SWIFT_WEBROOT/$SWIFT_BRANCH/$(echo $SWIFT_PLATFORM | tr -d .)$OS_ARCH_SUFFIX" \
-    && SWIFT_BIN_URL="$SWIFT_WEBDIR/$SWIFT_VERSION/$SWIFT_VERSION-$SWIFT_PLATFORM$OS_ARCH_SUFFIX.tar.gz" \
-    && SWIFT_SIG_URL="$SWIFT_BIN_URL.sig" \
-    && export DEBIAN_FRONTEND=noninteractive \
-    && export GNUPGHOME="$(mktemp -d)" \
-    && curl -fsSL "$SWIFT_BIN_URL" -o swift.tar.gz "$SWIFT_SIG_URL" -o swift.tar.gz.sig \
-    && gpg --batch --quiet --keyserver keyserver.ubuntu.com --recv-keys "$SWIFT_SIGNING_KEY" \
-    && gpg --batch --verify swift.tar.gz.sig swift.tar.gz \
-    && tar -xzf swift.tar.gz --directory / --strip-components=1 \
-    && chmod -R o+r /usr/lib/swift \
-    && rm -rf "$GNUPGHOME" swift.tar.gz.sig swift.tar.gz \
-    && rm -rf /var/lib/apt/lists/* \
-    && swift --version \
-    && chmod +x /tmp/install.sh \
-    && /tmp/install.sh && rm /tmp/install.sh \
-    && node -v \
-    && npm -v \
-    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
-    && rm -rf /var/lib/apt/lists/*
+        unzip \
+        uuid-dev \
+        zip \
+ && SWIFT_WEBDIR="$SWIFT_WEBROOT/$SWIFT_BRANCH/$(echo $SWIFT_PLATFORM | tr -d .)$OS_ARCH_SUFFIX" \
+ && SWIFT_BIN_URL="$SWIFT_WEBDIR/$SWIFT_VERSION/$SWIFT_VERSION-$SWIFT_PLATFORM$OS_ARCH_SUFFIX.tar.gz" \
+ && SWIFT_SIG_URL="$SWIFT_BIN_URL.sig" \
+ && export GNUPGHOME="$(mktemp -d)" \
+ && curl -fsSL \
+      "$SWIFT_BIN_URL" -o swift.tar.gz \
+      "$SWIFT_SIG_URL" -o swift.tar.gz.sig \
+ && gpg --batch --quiet --keyserver keyserver.ubuntu.com --recv-keys "$SWIFT_SIGNING_KEY" \
+ && gpg --batch --verify swift.tar.gz.sig swift.tar.gz \
+ && tar -xzf swift.tar.gz --directory / --strip-components=1 \
+ && chmod -R o+r /usr/lib/swift \
+ && rm -rf "$GNUPGHOME" swift.tar.gz.sig swift.tar.gz \
+ && swift --version \
+ && chmod +x /tmp/install.sh \
+ && /tmp/install.sh \
+ && rm /tmp/install.sh \
+ && pip install \
+      --no-cache-dir \
+      --target ${PYTHONPATH} \
+      --upgrade \
+        atom-tools \
+        blint \
+ && node -v \
+ && npm -v \
+ && apt-get purge -y --auto-remove \
+      -o APT::AutoRemove::RecommendsImportant=false \
+ && rm -rf /var/lib/apt/lists/*
+
 CMD ["/bin/bash"]
 
 
@@ -75,29 +99,39 @@ CMD ["/bin/bash"]
 # cdxgen-image
 FROM base AS cdxgen
 
+ARG VERSION=master
+
 LABEL maintainer="CycloneDX" \
+      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t $TAG -r /app --server" \
       org.opencontainers.image.authors="Team AppThreat <cloud@appthreat.com>" \
-      org.opencontainers.image.source="https://github.com/CycloneDX/cdxgen" \
-      org.opencontainers.image.url="https://github.com/CycloneDX/cdxgen" \
-      org.opencontainers.image.version="rolling" \
-      org.opencontainers.image.vendor="CycloneDX" \
+      org.opencontainers.image.description="Image with cdxgen SBOM generator for $LANGUAGE apps" \
       org.opencontainers.image.licenses="Apache-2.0" \
+      org.opencontainers.image.source="https://github.com/CycloneDX/cdxgen" \
       org.opencontainers.image.title="cdxgen" \
-      org.opencontainers.image.description="Rolling image with cdxgen SBOM generator for swift apps" \
-      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t ghcr.io/cyclonedx/cdxgen-debian-swift:v11 -r /app --server"
+      org.opencontainers.image.url="https://github.com/CycloneDX/cdxgen" \
+      org.opencontainers.image.vendor="CycloneDX" \
+      org.opencontainers.image.version="$VERSION"
 
 ENV CDXGEN_IN_CONTAINER=true \
     NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
-    PYTHONPATH=/opt/pypi
-ENV PATH=${PATH}:/usr/local/bin:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin
+    PATH=${PATH}:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin
 
 COPY . /opt/cdxgen
 
-RUN cd /opt/cdxgen && corepack enable && corepack pnpm install --config.strict-dep-builds=true --prod --package-import-method copy --frozen-lockfile && corepack pnpm cache delete \
-    && mkdir -p ${NODE_COMPILE_CACHE} \
-    && node /opt/cdxgen/bin/cdxgen.js --help \
-    && pip install --upgrade --no-cache-dir blint atom-tools --target /opt/pypi \
-    && rm -rf /root/.cache/node \
-    && chmod a-w -R /opt
+RUN set -e; \
+    cd /opt/cdxgen \
+ && corepack enable \
+ && corepack pnpm install \
+      --config.strict-dep-builds=true \
+      --frozen-lockfile \
+      --package-import-method copy \
+      --prod \
+ && corepack pnpm cache delete \
+ && mkdir -p ${NODE_COMPILE_CACHE} \
+ && node /opt/cdxgen/bin/cdxgen.js --help \
+ && rm -rf .npmrc /root/.cache/node \
+ && chmod a-w -R /opt
+
 WORKDIR /app
+
 ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
