[build] Changed image builds to make use of Nexus on self-hosted runs. (#2153)
Changed image builds to make use of Nexus on self-hosted runs.
Also refactored & reordered Dockerfiles.

Signed-off-by: Roland Asmann <roland.asmann@gmail.com>

diff --git a/ci/images/Dockerfile.java17 b/ci/images/Dockerfile.java17
--- a/ci/images/Dockerfile.java17
+++ b/ci/images/Dockerfile.java17
@@ -1,96 +1,123 @@
 # Base-image
 FROM registry.suse.com/bci/openjdk-devel:17 AS base
 
-ARG SBT_VERSION=1.11.2
-ARG MAVEN_VERSION=3.9.10
 ARG GRADLE_VERSION=8.14.2
+ARG MAVEN_VERSION=3.9.10
+ARG SBT_VERSION=1.11.2
 ARG SCALA_VERSION=3.6.4
 
-ENV SBT_VERSION=$SBT_VERSION \
-    SCALA_VERSION=$SCALA_VERSION \
-    SCALA_HOME="/opt/scala/${SCALA_VERSION}" \
-    MAVEN_VERSION=$MAVEN_VERSION \
-    GRADLE_VERSION=$GRADLE_VERSION \
+ENV GRADLE_HOME="/opt/gradle/${GRADLE_VERSION}" \
     GRADLE_OPTS="-Dorg.gradle.daemon=false" \
-    MAVEN_HOME="/opt/maven/${MAVEN_VERSION}" \
-    GRADLE_HOME="/opt/gradle/${GRADLE_VERSION}" \
-    SBT_HOME="/opt/sbt/${SBT_VERSION}" \
-    LC_ALL=en_US.UTF-8 \
+    GRADLE_VERSION=$GRADLE_VERSION \
     LANG=en_US.UTF-8 \
     LANGUAGE=en_US.UTF-8 \
+    LC_ALL=en_US.UTF-8 \
+    MAVEN_HOME="/opt/maven/${MAVEN_VERSION}" \
+    MAVEN_VERSION=$MAVEN_VERSION \
+    PYTHONPATH=/opt/pypi \
+    SBT_HOME="/opt/sbt/${SBT_VERSION}" \
+    SBT_VERSION=$SBT_VERSION \
+    SCALA_HOME="/opt/scala/${SCALA_VERSION}" \
+    SCALA_VERSION=$SCALA_VERSION \
     npm_config_python=/usr/bin/python3.11
-ENV PATH=${PATH}:${MAVEN_HOME}/bin:${GRADLE_HOME}/bin:${SCALA_HOME}/bin:${SBT_HOME}/bin:
+ENV PATH=${PATH}:/usr/local/bin:${PYTHONPATH}/bin:${MAVEN_HOME}/bin:${GRADLE_HOME}/bin:${SCALA_HOME}/bin:${SBT_HOME}/bin
 
 RUN set -e; \
     ARCH_NAME="$(rpm --eval '%{_arch}')"; \
-    url=; \
     case "${ARCH_NAME##*-}" in \
-        'x86_64') \
-            OS_ARCH_SUFFIX=''; \
-            GOBIN_VERSION='amd64'; \
-            ;; \
-        'aarch64') \
-            OS_ARCH_SUFFIX='-aarch64'; \
-            GOBIN_VERSION='arm64'; \
-            ;; \
-        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+      'amd64' | 'x86_64') \
+        GOBIN_VERSION='amd64'; \
+        ;; \
+      'aarch64' | 'arm64') \
+        GOBIN_VERSION='arm64'; \
+        ;; \
+      *) \
+        echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; \
+        exit 1 \
+        ;; \
     esac \
-    && zypper refresh && zypper --non-interactive update && zypper --non-interactive install -l --no-recommends git-core nodejs22 npm22 python311 python311-pip wget zip unzip make gawk \
-    && curl -s "https://get.sdkman.io" | bash \
-    && echo -e "sdkman_auto_answer=true\nsdkman_selfupdate_feature=false\nsdkman_auto_env=true\nsdkman_curl_connect_timeout=20\nsdkman_curl_max_time=0" >> $HOME/.sdkman/etc/config \
-    && source "$HOME/.sdkman/bin/sdkman-init.sh" \
-    && sdk install maven $MAVEN_VERSION \
-    && sdk install gradle $GRADLE_VERSION \
-    && sdk install scala $SCALA_VERSION \
-    && sdk install sbt $SBT_VERSION \
-    && mv /root/.sdkman/candidates/* /opt/ \
-    && curl -L --output /usr/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-${GOBIN_VERSION} \
-    && chmod +x /usr/bin/bazel \
-    && bazel --version \
-    && npm install -g corepack \
-    && zypper clean -a
+ && zypper refresh \
+ && zypper \
+      --non-interactive \
+        update \
+ && zypper \
+      --non-interactive \
+        install \
+        -l \
+        --no-recommends \
+          gawk \
+          git-core \
+          make \
+          nodejs22 \
+          npm22 \
+          python311 \
+          python311-pip \
+          unzip \
+          wget \
+          zip \
+ && curl -s "https://get.sdkman.io" | bash \
+ && echo -e "sdkman_auto_answer=true\nsdkman_selfupdate_feature=false\nsdkman_auto_env=true\nsdkman_curl_connect_timeout=20\nsdkman_curl_max_time=0" \
+      >> $HOME/.sdkman/etc/config \
+ && source "$HOME/.sdkman/bin/sdkman-init.sh" \
+ && sdk install maven $MAVEN_VERSION \
+ && sdk install gradle $GRADLE_VERSION \
+ && sdk install scala $SCALA_VERSION \
+ && sdk install sbt $SBT_VERSION \
+ && mv /root/.sdkman/candidates/* /opt/ \
+ && curl -L --output /usr/bin/bazel \
+      https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-${GOBIN_VERSION} \
+ && chmod +x /usr/bin/bazel \
+ && bazel --version \
+ && pip install \
+      --no-cache-dir \
+      --target ${PYTHONPATH} \
+      --upgrade \
+        atom-tools \
+ && atom-tools --help \
+ && npm install -g \
+      corepack \
+ && zypper clean -a
+
+CMD ["/bin/bash"]
+
+
 
 # cdxgen-image
 FROM base AS cdxgen
 
+ARG VERSION=master
+
 LABEL maintainer="CycloneDX" \
+      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t $TAG -r /app --server" \
       org.opencontainers.image.authors="Team AppThreat <cloud@appthreat.com>" \
-      org.opencontainers.image.source="https://github.com/CycloneDX/cdxgen" \
-      org.opencontainers.image.url="https://github.com/CycloneDX/cdxgen" \
-      org.opencontainers.image.version="rolling" \
-      org.opencontainers.image.vendor="CycloneDX" \
+      org.opencontainers.image.description="Image with cdxgen SBOM generator for $LANGUAGE apps" \
       org.opencontainers.image.licenses="Apache-2.0" \
+      org.opencontainers.image.source="https://github.com/CycloneDX/cdxgen" \
       org.opencontainers.image.title="cdxgen" \
-      org.opencontainers.image.description="Rolling image with cdxgen SBOM generator for Java 17 apps" \
-      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t ghcr.io/cyclonedx/cdxgen-java17:v11 -r /app --server"
+      org.opencontainers.image.url="https://github.com/CycloneDX/cdxgen" \
+      org.opencontainers.image.vendor="CycloneDX" \
+      org.opencontainers.image.version="$VERSION"
 
 ENV CDXGEN_IN_CONTAINER=true \
-    PYTHONPATH=/opt/pypi \
-    NODE_COMPILE_CACHE="/opt/cdxgen-node-cache"
-ENV PATH=${PATH}:/usr/local/bin:/opt/cdxgen/node_modules/.bin:${PYTHONPATH}/bin
+    NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
+    PATH=${PATH}:/opt/cdxgen/node_modules/.bin
 
 COPY . /opt/cdxgen
 
 RUN set -e; \
-    ARCH_NAME="$(rpm --eval '%{_arch}')"; \
-    case "${ARCH_NAME##*-}" in \
-        'x86_64') \
-            ATOM_ARCH_SUFFIX='amd64'; \
-            ;; \
-        'arm64') \
-            ATOM_ARCH_SUFFIX='arm64'; \
-            ;; \
-        'aarch64') \
-            ATOM_ARCH_SUFFIX='arm64'; \
-            ;; \
-        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
-    esac \
-    && cd /opt/cdxgen && corepack enable && corepack pnpm install --config.strict-dep-builds=true --prod --package-import-method copy --frozen-lockfile && corepack pnpm cache delete \
-    && mkdir -p ${NODE_COMPILE_CACHE} \
-    && node /opt/cdxgen/bin/cdxgen.js --help \
-    && pip install --upgrade --no-cache-dir atom-tools --target /opt/pypi \
-    && atom-tools --help \
-    && rm -rf /root/.cache/node \
-    && chmod a-w -R /opt
+    cd /opt/cdxgen \
+ && corepack enable \
+ && corepack pnpm install \
+      --config.strict-dep-builds=true \
+      --frozen-lockfile \
+      --package-import-method copy \
+      --prod \
+ && corepack pnpm cache delete \
+ && mkdir -p ${NODE_COMPILE_CACHE} \
+ && node /opt/cdxgen/bin/cdxgen.js --help \
+ && rm -rf .npmrc /root/.cache/node \
+ && chmod a-w -R /opt
+
 WORKDIR /app
+
 ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
diff --git a/ci/images/debian/Dockerfile.dotnet10 b/ci/images/debian/Dockerfile.dotnet10
--- a/ci/images/debian/Dockerfile.dotnet10
+++ b/ci/images/debian/Dockerfile.dotnet10
@@ -4,41 +4,78 @@ FROM mcr.microsoft.com/dotnet/sdk:10.0-preview-trixie-slim AS base
 # renovate: datasource=docker depName=node
 ARG NODE_VERSION=24.6.0
 
-ENV DOTNET_GENERATE_ASPNET_CERTIFICATE=false \
+ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
+    DOTNET_GENERATE_ASPNET_CERTIFICATE=false \
     DOTNET_NOLOGO=true \
+    DOTNET_RUNNING_IN_CONTAINER=true \
     DOTNET_USE_POLLING_FILE_WATCHER=false \
     NUGET_XMLDOC_MODE=skip \
-    DOTNET_RUNNING_IN_CONTAINER=true \
-    DOTNET_CLI_TELEMETRY_OPTOUT=1 \
-    NVM_DIR="/root/.nvm"
-ENV PATH=${PATH}:${NVM_DIR}/versions/node/v${NODE_VERSION}/bin:/usr/local/bin:/root/.local/bin
+    NVM_DIR="/root/.nvm" \
+    PYTHONPATH=/opt/pypi
+ENV PATH=${PATH}:/usr/local/bin:/root/.local/bin:${NVM_DIR}/versions/node/v${NODE_VERSION}/bin
 
 COPY ci/images/debian/install.sh /tmp/
 
-RUN set -e;\
-    apt-get update && apt-get install -qq -y --no-install-recommends curl bash bzip2 git-core zip unzip make gawk \
-        autotools-dev autoconf-archive gettext intltool libadwaita-1-dev \
-    && apt-get install -qq -y build-essential mono-devel mono-xbuild python3 python3-pip python3-dev locales \
-    && chmod +x /tmp/install.sh \
-    && /tmp/install.sh && rm /tmp/install.sh \
-    && node -v \
-    && npm -v \
-    && corepack -v \
-    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
-    && rm -rf /var/lib/apt/lists/* \
-    && dotnet --list-sdks \
-    && ARCH_NAME="$(dpkg --print-architecture)"; \
-       url=; \
-       case "${ARCH_NAME##*-}" in \
-            'amd64') \
-                dotnet workload install android wasm-tools wasm-tools-net6 wasm-tools-net7 \
-                ;; \
-            'arm64') \
-                dotnet workload install wasm-tools \
-                ;; \
-            *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
-       esac; \
+RUN set -e; \
+    apt-get update \
+ && apt-get install -qq -y --no-install-recommends \
+      autoconf-archive \
+      autotools-dev \
+      bash \
+      bzip2 \
+      curl \
+      gawk \
+      gettext \
+      git-core \
+      intltool \
+      libadwaita-1-dev \
+      make \
+      unzip \
+      zip \
+ && apt-get install -qq -y \
+      build-essential \
+      locales \
+      mono-devel \
+      mono-xbuild \
+      python3 \
+      python3-dev \
+      python3-pip \
+ && chmod +x /tmp/install.sh \
+ && /tmp/install.sh \
+ && rm /tmp/install.sh \
+ && pip install \
+      --no-cache-dir \
+      --target ${PYTHONPATH} \
+      --upgrade \
+        atom-tools \
+        blint \
+ && node -v \
+ && npm -v \
+ && apt-get purge -y --auto-remove \
+      -o APT::AutoRemove::RecommendsImportant=false \
+ && rm -rf /var/lib/apt/lists/* \
+ && dotnet --list-sdks \
+ && set -e; \
+    ARCH_NAME="$(dpkg --print-architecture)"; \
+    case "${ARCH_NAME##*-}" in \
+      'amd64' | 'x86_64') \
+        dotnet workload install \
+          android \
+          wasm-tools \
+          wasm-tools-net6 \
+          wasm-tools-net7 \
+        ;; \
+      'aarch64' | 'arm64') \
+        dotnet workload install \
+          wasm-tools \
+        ;; \
+      *) \
+        echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; \
+        exit 1 \
+        ;; \
+    esac; \
     dotnet workload list
+
 CMD ["/bin/bash"]
 
 
@@ -46,29 +83,39 @@ CMD ["/bin/bash"]
 # cdxgen-image
 FROM base AS cdxgen
 
+ARG VERSION=latest
+
 LABEL maintainer="CycloneDX" \
+      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t $TAG -r /app --server" \
       org.opencontainers.image.authors="Team AppThreat <cloud@appthreat.com>" \
-      org.opencontainers.image.source="https://github.com/CycloneDX/cdxgen" \
-      org.opencontainers.image.url="https://github.com/CycloneDX/cdxgen" \
-      org.opencontainers.image.version="rolling" \
-      org.opencontainers.image.vendor="CycloneDX" \
+      org.opencontainers.image.description="Image with cdxgen SBOM generator for $LANGUAGE apps" \
       org.opencontainers.image.licenses="Apache-2.0" \
+      org.opencontainers.image.source="https://github.com/CycloneDX/cdxgen" \
       org.opencontainers.image.title="cdxgen" \
-      org.opencontainers.image.description="Rolling image with cdxgen SBOM generator for dotnet 10 apps" \
-      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t ghcr.io/cyclonedx/cdxgen-debian-dotnet10:v11 -r /app --server"
+      org.opencontainers.image.url="https://github.com/CycloneDX/cdxgen" \
+      org.opencontainers.image.vendor="CycloneDX" \
+      org.opencontainers.image.version="$VERSION"
 
 ENV CDXGEN_IN_CONTAINER=true \
     NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
-    PYTHONPATH=/opt/pypi
-ENV PATH=${PATH}:/usr/local/bin:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin
+    PATH=${PATH}:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin
 
 COPY . /opt/cdxgen
 
-RUN cd /opt/cdxgen && corepack enable && corepack pnpm install --config.strict-dep-builds=true --prod --package-import-method copy --frozen-lockfile && corepack pnpm cache delete \
-    && mkdir -p ${NODE_COMPILE_CACHE} \
-    && node /opt/cdxgen/bin/cdxgen.js --help \
-    && pip install --upgrade --no-cache-dir blint atom-tools --target ${PYTHONPATH} \
-    && rm -rf /root/.cache/node \
-    && chmod a-w -R /opt
+RUN set -e; \
+    cd /opt/cdxgen \
+ && corepack enable \
+ && corepack pnpm install \
+      --config.strict-dep-builds=true \
+      --frozen-lockfile \
+      --package-import-method copy \
+      --prod \
+ && corepack pnpm cache delete \
+ && mkdir -p ${NODE_COMPILE_CACHE} \
+ && node /opt/cdxgen/bin/cdxgen.js --help \
+ && rm -rf .npmrc /root/.cache/node \
+ && chmod a-w -R /opt
+
 WORKDIR /app
+
 ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
diff --git a/ci/images/debian/Dockerfile.dotnet6 b/ci/images/debian/Dockerfile.dotnet6
--- a/ci/images/debian/Dockerfile.dotnet6
+++ b/ci/images/debian/Dockerfile.dotnet6
@@ -4,30 +4,63 @@ FROM mcr.microsoft.com/dotnet/sdk:6.0-bookworm-slim AS base
 # renovate: datasource=docker depName=node
 ARG NODE_VERSION=22.17.0
 
-ENV DOTNET_GENERATE_ASPNET_CERTIFICATE=false \
+ENV DOTNET_CLI_TELEMETRY_OPTOUT=1 \
+    DOTNET_GENERATE_ASPNET_CERTIFICATE=false \
     DOTNET_NOLOGO=true \
+    DOTNET_RUNNING_IN_CONTAINER=true \
     DOTNET_USE_POLLING_FILE_WATCHER=false \
     NUGET_XMLDOC_MODE=skip \
-    DOTNET_RUNNING_IN_CONTAINER=true \
-    DOTNET_CLI_TELEMETRY_OPTOUT=1 \
-    NVM_DIR="/root/.nvm"
-ENV PATH=${PATH}:${NVM_DIR}/versions/node/v${NODE_VERSION}/bin:/usr/local/bin:/root/.local/bin
+    NVM_DIR="/root/.nvm" \
+    PYTHONPATH=/opt/pypi
+ENV PATH=${PATH}:/usr/local/bin:/root/.local/bin:${NVM_DIR}/versions/node/v${NODE_VERSION}/bin
 
 COPY ci/images/debian/install.sh /tmp/
 
-RUN apt-get update && apt-get install -qq -y --no-install-recommends gcc g++ curl bash bzip2 git-core zip unzip make gawk \
-    && apt-get install -qq -y build-essential mono-devel mono-xbuild nuget python3 python3-pip python3-dev locales \
-    && chmod +x /tmp/install.sh \
-    && /tmp/install.sh && rm /tmp/install.sh \
-    && node -v \
-    && npm -v \
-    && rm -rf /usr/lib/nuget \
-    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
-    && rm -rf /var/lib/apt/lists/*
+RUN set -e; \
+    apt-get update \
+ && apt-get install -qq -y --no-install-recommends \
+      bash \
+      bzip2 \
+      curl \
+      gawk \
+      gcc \
+      git-core \
+      g++ \
+      make \
+      unzip \
+      zip \
+ && apt-get install -qq -y \
+      build-essential \
+      locales \
+      mono-devel \
+      mono-xbuild \
+      nuget \
+      python3 \
+      python3-dev \
+      python3-pip \
+ && chmod +x /tmp/install.sh \
+ && /tmp/install.sh \
+ && rm /tmp/install.sh \
+ && pip install \
+      --no-cache-dir \
+      --target ${PYTHONPATH} \
+      --upgrade \
+        atom-tools \
+        blint \
+ && node -v \
+ && npm -v \
+ && rm -rf /usr/lib/nuget \
+ && apt-get purge -y --auto-remove \
+      -o APT::AutoRemove::RecommendsImportant=false \
+ && rm -rf /var/lib/apt/lists/*
+
 COPY ci/images/nuget /usr/lib/nuget
-RUN mv /usr/lib/nuget/nuget.exe /usr/lib/nuget/NuGet.exe \
-    && dotnet --list-sdks \
-    && nuget help
+
+RUN set -e; \
+    mv /usr/lib/nuget/nuget.exe /usr/lib/nuget/NuGet.exe \
+ && dotnet --list-sdks \
+ && nuget help
+
 CMD ["/bin/bash"]
 
 
@@ -35,51 +68,57 @@ CMD ["/bin/bash"]
 # cdxgen-image
 FROM base AS cdxgen
 
+ARG VERSION=master
+
 LABEL maintainer="CycloneDX" \
+      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t $TAG -r /app --server" \
       org.opencontainers.image.authors="Team AppThreat <cloud@appthreat.com>" \
-      org.opencontainers.image.source="https://github.com/CycloneDX/cdxgen" \
-      org.opencontainers.image.url="https://github.com/CycloneDX/cdxgen" \
-      org.opencontainers.image.version="rolling" \
-      org.opencontainers.image.vendor="CycloneDX" \
+      org.opencontainers.image.description="Image with cdxgen SBOM generator for $LANGUAGE apps" \
       org.opencontainers.image.licenses="Apache-2.0" \
+      org.opencontainers.image.source="https://github.com/CycloneDX/cdxgen" \
       org.opencontainers.image.title="cdxgen" \
-      org.opencontainers.image.description="Rolling image with cdxgen SBOM generator for dotnet 6 apps" \
-      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t ghcr.io/cyclonedx/cdxgen-debian-dotnet6:v11 -r /app --server"
+      org.opencontainers.image.url="https://github.com/CycloneDX/cdxgen" \
+      org.opencontainers.image.vendor="CycloneDX" \
+      org.opencontainers.image.version="$VERSION"
 
 ENV CDXGEN_IN_CONTAINER=true \
+    DOSAI_CMD=/usr/local/bin/dosai \
     NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
-    PYTHONPATH=/opt/pypi \
-    DOSAI_CMD=/usr/local/bin/dosai
-ENV PATH=${PATH}:/usr/local/bin:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin
+    PATH=${PATH}:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin
 
 COPY . /opt/cdxgen
 
 RUN set -e; \
     ARCH_NAME="$(dpkg --print-architecture)"; \
-    url=; \
     case "${ARCH_NAME##*-}" in \
-        'amd64') \
-            DOSAI_ARCH_SUFFIX='-full'; \
-            ;; \
-        'x86_64') \
-            DOSAI_ARCH_SUFFIX='-full'; \
-            ;; \
-        'arm64') \
-            DOSAI_ARCH_SUFFIX='-linux-arm64-full'; \
-            ;; \
-        'aarch64') \
-            DOSAI_ARCH_SUFFIX='-linux-arm64-full'; \
-            ;; \
-        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+      'amd64' | 'x86_64') \
+         DOSAI_ARCH_SUFFIX='-full'; \
+         ;; \
+      'aarch64' | 'arm64') \
+         DOSAI_ARCH_SUFFIX='-linux-arm64-full'; \
+         ;; \
+      *) \
+         echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; \
+         exit 1 \
+         ;; \
     esac \
-    && cd /opt/cdxgen && corepack enable && corepack pnpm install --config.strict-dep-builds=true --prod --package-import-method copy --frozen-lockfile && corepack pnpm cache delete \
-    && curl -L https://github.com/owasp-dep-scan/dosai/releases/latest/download/Dosai${DOSAI_ARCH_SUFFIX} -o /usr/local/bin/dosai \
-    && chmod +x /usr/local/bin/dosai \
-    && dosai --help \
-    && mkdir -p ${NODE_COMPILE_CACHE} \
-    && node /opt/cdxgen/bin/cdxgen.js --help \
-    && pip install --upgrade --no-cache-dir blint atom-tools --target ${PYTHONPATH} \
-    && rm -rf /root/.cache/node \
-    && chmod a-w -R /opt
+ && cd /opt/cdxgen \
+ && corepack enable \
+ && corepack pnpm install \
+      --config.strict-dep-builds=true \
+      --frozen-lockfile \
+      --package-import-method copy \
+      --prod \
+ && corepack pnpm cache delete \
+ && curl -L https://github.com/owasp-dep-scan/dosai/releases/latest/download/Dosai${DOSAI_ARCH_SUFFIX} \
+      -o /usr/local/bin/dosai \
+ && chmod +x /usr/local/bin/dosai \
+ && dosai --help \
+ && mkdir -p ${NODE_COMPILE_CACHE} \
+ && node /opt/cdxgen/bin/cdxgen.js --help \
+ && rm -rf .npmrc /root/.cache/node \
+ && chmod a-w -R /opt
+
 WORKDIR /app
+
 ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
diff --git a/ci/images/opensuse/Dockerfile.rolling b/ci/images/opensuse/Dockerfile.rolling
--- a/ci/images/opensuse/Dockerfile.rolling
+++ b/ci/images/opensuse/Dockerfile.rolling
@@ -1,85 +1,125 @@
 # Base-image
 FROM opensuse/tumbleweed:latest AS base
 
+ARG DOTNET_SDK_VERSION=9.0.100
+ARG GRADLE_VERSION=8.14.2
 ARG MAVEN_VERSION=4.0.0-rc-3
 ARG SBT_VERSION=1.11.2
-ARG GRADLE_VERSION=8.14.2
-ARG DOTNET_SDK_VERSION=9.0.100
 ARG SCALA_VERSION=3.7.1
 
 ENV CC=gcc \
-    SBT_VERSION=$SBT_VERSION \
-    MAVEN_VERSION=$MAVEN_VERSION \
-    GRADLE_VERSION=$GRADLE_VERSION \
-    DOTNET_SDK_VERSION=$DOTNET_SDK_VERSION \
+    DOTNET_CLI_TELEMETRY_OPTOUT=1 \
     DOTNET_GENERATE_ASPNET_CERTIFICATE=false \
     DOTNET_NOLOGO=true \
-    DOTNET_USE_POLLING_FILE_WATCHER=false \
+    DOTNET_ROOT=/usr/share/dotnet \
     DOTNET_RUNNING_IN_CONTAINER=true \
-    DOTNET_CLI_TELEMETRY_OPTOUT=1 \
-    NUGET_XMLDOC_MODE=skip \
-    MAVEN_HOME="/opt/maven/${MAVEN_VERSION}" \
+    DOTNET_SDK_VERSION=$DOTNET_SDK_VERSION \
+    DOTNET_USE_POLLING_FILE_WATCHER=false \
     GRADLE_HOME="/opt/gradle/${GRADLE_VERSION}" \
-    SBT_HOME="/opt/sbt/${SBT_VERSION}" \
-    SCALA_VERSION=$SCALA_VERSION \
-    SCALA_HOME="/opt/scala/${SCALA_VERSION}" \
-    LC_ALL=en_US.UTF-8 \
+    GRADLE_VERSION=$GRADLE_VERSION \
     LANG=en_US.UTF-8 \
     LANGUAGE=en_US.UTF-8 \
-    DOTNET_ROOT=/usr/share/dotnet \
-    PYTHONPATH=/opt/pypi
+    LC_ALL=en_US.UTF-8 \
+    MAVEN_HOME="/opt/maven/${MAVEN_VERSION}" \
+    MAVEN_VERSION=$MAVEN_VERSION \
+    NUGET_XMLDOC_MODE=skip \
+    PYTHONPATH=/opt/pypi \
+    SBT_HOME="/opt/sbt/${SBT_VERSION}" \
+    SBT_VERSION=$SBT_VERSION \
+    SCALA_HOME="/opt/scala/${SCALA_VERSION}" \
+    SCALA_VERSION=$SCALA_VERSION
+ENV PATH=${PATH}:/usr/local/bin:${MAVEN_HOME}/bin:${GRADLE_HOME}/bin:${SCALA_HOME}/bin:${SBT_HOME}/bin:${PYTHONPATH}/bin:/usr/share/dotnet
 
-ENV PATH=${PATH}:${MAVEN_HOME}/bin:${GRADLE_HOME}/bin:${SCALA_HOME}/bin:${SBT_HOME}/bin:/usr/local/bin:${PYTHONPATH}/bin:/usr/share/dotnet
 RUN set -e; \
     ARCH_NAME="$(rpm --eval '%{_arch}')"; \
-    url=; \
     case "${ARCH_NAME##*-}" in \
-        'x86_64') \
-            OS_ARCH_SUFFIX='x64'; \
-            GOBIN_VERSION='amd64'; \
-            ;; \
-        'aarch64') \
-            OS_ARCH_SUFFIX='arm64'; \
-            GOBIN_VERSION='arm64'; \
-            ;; \
-        *) echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; exit 1 ;; \
+      'amd64' | 'x86_64') \
+        OS_ARCH_SUFFIX='x64'; \
+        GOBIN_VERSION='amd64'; \
+        ;; \
+      'aarch64' | 'arm64') \
+        OS_ARCH_SUFFIX='arm64'; \
+        GOBIN_VERSION='arm64'; \
+        ;; \
+      *) \
+        echo >&2 "error: unsupported architecture: '$ARCH_NAME'"; \
+        exit 1 \
+        ;; \
     esac \
-    && zypper refresh && zypper --non-interactive dup && zypper --non-interactive install -l --no-recommends gcc14 gcc14-c++ gcc14-fortran \
-        bzip2 python312 python312-devel python312-pip findutils java-24-openjdk-devel \
-        libicu-devel git-core wget zip unzip make gawk nodejs22 npm22 rust1.86 cargo1.86 \
-    && update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-14 10 \
-    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 10 \
-    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 10 \
-    && update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-14 10 \
-    && update-alternatives --install /usr/bin/python python /usr/bin/python3.12 10 \
-    && curl -s "https://get.sdkman.io" | bash \
-    && echo -e "sdkman_auto_answer=true\nsdkman_selfupdate_feature=false\nsdkman_auto_env=true\nsdkman_curl_connect_timeout=20\nsdkman_curl_max_time=0" >> $HOME/.sdkman/etc/config \
-    && source "$HOME/.sdkman/bin/sdkman-init.sh" \
-    && sdk install maven $MAVEN_VERSION \
-    && sdk install gradle $GRADLE_VERSION \
-    && sdk install scala $SCALA_VERSION \
-    && sdk install sbt $SBT_VERSION \
-    && sdk offline enable \
-    && mv /root/.sdkman/candidates/* /opt/ \
-    && rm -rf /root/.sdkman \
-    && curl -fSL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-${OS_ARCH_SUFFIX}.tar.gz \
-    && mkdir -p /usr/share/dotnet \
-    && tar -xf dotnet.tar.gz -C /usr/share/dotnet \
-    && rm dotnet.tar.gz \
-    && dotnet --list-sdks \
-    && mkdir ${PYTHONPATH} \
-    && python -m pip install --no-cache-dir --upgrade poetry pipenv blint atom-tools custom-json-diff uv --target ${PYTHONPATH} \
-    && node -v \
-    && npm -v \
-    && npm install -g corepack \
-    && poetry --version \
-    && pipenv --version \
-    && blint --help \
-    && gcc --version \
-    && curl -L --output /usr/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-${GOBIN_VERSION} \
-    && chmod +x /usr/bin/bazel \
-    && bazel --version \
-    && zypper clean -a
+ && zypper refresh \
+ && zypper \
+      --non-interactive \
+        dup \
+ && zypper \
+      --non-interactive \
+        install \
+        -l \
+        --no-recommends \
+          bzip2 \
+          cargo1.86 \
+          findutils \
+          gawk \
+          gcc14 \
+          gcc14-c++ \
+          gcc14-fortran \
+          git-core \
+          java-24-openjdk-devel \
+          libicu-devel \
+          make \
+          nodejs22 \
+          npm22 \
+          python312 \
+          python312-devel \
+          python312-pip \
+          rust1.86 \
+          unzip \
+          wget \
+          zip \
+ && update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-14 10 \
+ && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 10 \
+ && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 10 \
+ && update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-14 10 \
+ && update-alternatives --install /usr/bin/python python /usr/bin/python3.12 10 \
+ && curl -s "https://get.sdkman.io" | bash \
+ && echo -e "sdkman_auto_answer=true\nsdkman_selfupdate_feature=false\nsdkman_auto_env=true\nsdkman_curl_connect_timeout=20\nsdkman_curl_max_time=0" \
+    >> $HOME/.sdkman/etc/config \
+ && source "$HOME/.sdkman/bin/sdkman-init.sh" \
+ && sdk install maven $MAVEN_VERSION \
+ && sdk install gradle $GRADLE_VERSION \
+ && sdk install scala $SCALA_VERSION \
+ && sdk install sbt $SBT_VERSION \
+ && sdk offline enable \
+ && mv /root/.sdkman/candidates/* /opt/ \
+ && rm -rf /root/.sdkman \
+ && curl -fSL --output dotnet.tar.gz \
+      https://dotnetcli.azureedge.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-${OS_ARCH_SUFFIX}.tar.gz \
+ && mkdir -p /usr/share/dotnet \
+ && tar -xf dotnet.tar.gz -C /usr/share/dotnet \
+ && rm dotnet.tar.gz \
+ && dotnet --list-sdks \
+ && mkdir ${PYTHONPATH} \
+ && python -m pip install \
+      --no-cache-dir \
+      --target ${PYTHONPATH} \
+      --upgrade \
+        atom-tools \
+        blint \
+        custom-json-diff \
+        pipenv \
+        poetry \
+        uv \
+ && node -v \
+ && npm -v \
+ && npm install -g corepack \
+ && poetry --version \
+ && pipenv --version \
+ && blint --help \
+ && gcc --version \
+ && curl -L --output /usr/bin/bazel \
+      https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-${GOBIN_VERSION} \
+ && chmod +x /usr/bin/bazel \
+ && bazel --version \
+ && zypper clean -a
 
 CMD ["/bin/bash"]
 
@@ -88,29 +128,41 @@ CMD ["/bin/bash"]
 # cdxgen-image
 FROM base AS cdxgen
 
+
 LABEL maintainer="CycloneDX" \
+      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t $TAG -r /app --server" \
       org.opencontainers.image.authors="Team AppThreat <cloud@appthreat.com>" \
-      org.opencontainers.image.source="https://github.com/CycloneDX/cdxgen" \
-      org.opencontainers.image.url="https://github.com/CycloneDX/cdxgen" \
-      org.opencontainers.image.version="rolling" \
-      org.opencontainers.image.vendor="CycloneDX" \
-      org.opencontainers.image.licenses="Apache-2.0" \
-      org.opencontainers.image.title="cdxgen" \
       org.opencontainers.image.description="Rolling image with cdxgen SBOM generator based on tumbleweed" \
-      org.opencontainers.docker.cmd="docker run --rm -v /tmp:/tmp -p 9090:9090 -v $(pwd):/app:rw -t ghcr.io/cyclonedx/cdxgen-rolling:v11 -r /app --server"
+      org.opencontainers.image.licenses="Apache-2.0" \
+      org.opencontainers.image.source="https://github.com/CycloneDX/cdxgen" \
+      org.opencontainers.image.title="cdxgen" \
+      org.opencontainers.image.url="https://github.com/CycloneDX/cdxgen" \
+      org.opencontainers.image.vendor="CycloneDX" \
+      org.opencontainers.image.version="rolling"
 
 ENV CDXGEN_DEBUG_MODE=debug \
-    SCAN_DEBUG_MODE=debug \
     CDXGEN_IN_CONTAINER=true \
-    NODE_COMPILE_CACHE="/opt/cdxgen-node-cache"
-ENV PATH=${PATH}:/usr/local/bin:${PYTHONPATH}/bin:/opt/cdxgen/node_modules/.bin
+    NODE_COMPILE_CACHE="/opt/cdxgen-node-cache" \
+    PATH=${PATH}:/opt/cdxgen/node_modules/.bin \
+    SCAN_DEBUG_MODE=debug
 
 COPY . /opt/cdxgen
 
-RUN cd /opt/cdxgen && corepack enable && corepack pnpm install --config.strict-dep-builds=true --prod --package-import-method copy --frozen-lockfile && corepack pnpm cache delete \
-    && mkdir -p ${NODE_COMPILE_CACHE} \
-    && node /opt/cdxgen/bin/cdxgen.js --help \
-    && rm -rf /root/.cache/node \
-    && chmod a-w -R /opt
+RUN set -e; \
+    cd /opt/cdxgen \
+ && corepack enable \
+ && corepack pnpm install \
+      --config.strict-dep-builds=true \
+      --frozen-lockfile \
+      --package-import-method copy \
+      --prod \
+ && corepack pnpm cache delete \
+ && mkdir -p ${NODE_COMPILE_CACHE} \
+ && node /opt/cdxgen/bin/cdxgen.js --help \
+ && rm -rf .npmrc /root/.cache/node \
+ && zypper clean -a \
+ && chmod a-w -R /opt
+
 WORKDIR /app
+
 ENTRYPOINT ["node", "/opt/cdxgen/bin/cdxgen.js"]
